version: "3.8"

services:
  freshmarket-backend:
    image: freshmarket-backend:latest
    restart: always
    ports:
      - "13582:13582"
    environment:
      PROD: "true"
      FASTIFY_PORT: "13582"
      TRUST_PROXY: "true"
      DATABASE_HOST: "213.171.9.157"
    network_mode: "host"
